version: '3'
services:
  villaflor:
    build:
      context: ./docker/PHP8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-20}'
    image: villaflor-8.0/app
    restart: always
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER:-501}'
      LARAVEL_VILLAFLOR: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - villaflor
      - backend
      - nginx-pm_default
networks:
  nginx-pm_default:
    external:
      name: nginx-pm_default
  backend:
    external:
      name: backend_network
  villaflor:
    driver: bridge
